// <auto-generated />
using System;
using HealthMate.Infrastructure.Data.DbHelper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthMate.Infrastructure.Migrations
{
    [DbContext(typeof(HealthMateContext))]
    partial class HealthMateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Condition.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Condition_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("integer")
                        .HasColumnName("AddedBy");

                    b.Property<int?>("BodySiteId")
                        .HasColumnType("integer")
                        .HasColumnName("BodySiteId");

                    b.Property<int>("ClinicalStatus")
                        .HasColumnType("integer")
                        .HasColumnName("ClinicalStatus");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateRecorded");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("integer")
                        .HasColumnName("Disease_Id");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("integer")
                        .HasColumnName("EncounterId");

                    b.Property<string>("FhirId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("Condition_Fhir_Id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<bool>("IsChronic")
                        .HasColumnType("boolean")
                        .HasColumnName("isChronic");

                    b.Property<bool>("IsOngoing")
                        .HasColumnType("boolean")
                        .HasColumnName("isOngoing");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("Note");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("PaientId");

                    b.Property<int>("Recorder")
                        .HasColumnType("integer")
                        .HasColumnName("Recorder");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("Severity");

                    b.HasKey("Id");

                    b.HasIndex("BodySiteId");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("EncounterId");

                    b.HasIndex("PatientId");

                    b.ToTable("Conditions", (string)null);
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Encounter.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Encounter_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDate");

                    b.Property<string>("FhirId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("Encounter_Fhir_Id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<int>("HealthCareProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("HealthCareProviderId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("Location");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("Note");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("PatientId");

                    b.Property<string>("ReasonToVisit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Reason_To_Visit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDate");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("EncounterStatus");

                    b.Property<string>("TreatmentPlan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Treatment_Plan");

                    b.HasKey("Id");

                    b.HasIndex("HealthCareProviderId");

                    b.HasIndex("PatientId");

                    b.ToTable("Encounters", (string)null);
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Observation.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Observation_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BodySiteId")
                        .HasColumnType("integer")
                        .HasColumnName("BodySiteId");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("Category");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("Code");

                    b.Property<string>("CodeDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("CodeDisplayName");

                    b.Property<DateTime>("DateOfObservation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateOfObservation");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("integer")
                        .HasColumnName("EncounterId");

                    b.Property<string>("FhirId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("Observation_Fhir_Id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<string>("Interpretation")
                        .HasColumnType("text")
                        .HasColumnName("Interpertation");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted");

                    b.Property<string>("NameIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NameIdentifier");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("PatientId");

                    b.Property<decimal?>("ValueQuantity")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("ValueQuanitity");

                    b.Property<string>("ValueUnit")
                        .HasColumnType("text")
                        .HasColumnName("ValueUnit");

                    b.HasKey("Id");

                    b.HasIndex("BodySiteId")
                        .IsUnique();

                    b.HasIndex("EncounterId");

                    b.HasIndex("PatientId");

                    b.ToTable("Observations", (string)null);
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Patient.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Patient_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FhirId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("Patient_Fhir_Id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalIdImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("FhirId")
                        .HasDatabaseName("IX_Patients_Patient_Fhir_Id_Active")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Patient.PatientAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Reaction")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Substance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "IsActive");

                    b.ToTable("PatientAllergies", (string)null);
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Prescription.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PrescriptionId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EncounterId")
                        .HasColumnType("integer")
                        .HasColumnName("EncounterId");

                    b.Property<string>("NameIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NameIdentifier");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("PatientId");

                    b.Property<DateTime>("PrescriptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PrescriptionDate");

                    b.Property<string>("PrescriptionImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("PrescriptionImageUrl");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("Publisher");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Prescription.PrescriptionMedicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PatientMedicineId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AddedDate");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Dosage");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer")
                        .HasColumnName("DurationInDays");

                    b.Property<int>("FrequencyInHours")
                        .HasColumnType("integer")
                        .HasColumnName("FrequencyInHours");

                    b.Property<bool>("IsPrescribed")
                        .HasColumnType("boolean")
                        .HasColumnName("IsPrescribed");

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer")
                        .HasColumnName("MedicineId");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("PatientId");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("PrescriptionId");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PatientMedicines", (string)null);
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.Admin", b =>
                {
                    b.Property<int>("Admin_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Admin_Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Admin_Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.Animal", b =>
                {
                    b.Property<int>("Animal_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Animal_Id"));

                    b.Property<string>("Animal_Fhir_Id")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Owner_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Animal_Id");

                    b.HasIndex("Owner_Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.BodySite", b =>
                {
                    b.Property<int>("BodySite_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BodySite_Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BodySite_Id");

                    b.ToTable("BodySites");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.Disease", b =>
                {
                    b.Property<int>("Disease_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Disease_Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Display_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ICD11_Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scientific_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Disease_Id");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.HealthCareProvider", b =>
                {
                    b.Property<int>("HealthCareProvider_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HealthCareProvider_Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOnJoin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.HasKey("HealthCareProvider_Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("HealthCareProviders");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.LabTest", b =>
                {
                    b.Property<int>("LabTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabTestId"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LabTestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("patientId")
                        .HasColumnType("integer");

                    b.HasKey("LabTestId");

                    b.HasIndex("patientId");

                    b.ToTable("LabTests");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.LabTestAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValueUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LabTestAttributes");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.LabTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LabTestAttributeId")
                        .HasColumnType("integer");

                    b.Property<int>("LabTestId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("LabTestAttributeId");

                    b.HasIndex("LabTestId");

                    b.ToTable("LabTestResults");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.MedicalImage", b =>
                {
                    b.Property<int>("MedicalImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MedicalImageId"));

                    b.Property<string>("Interpertation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeRecorded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("paitentId")
                        .HasColumnType("integer");

                    b.HasKey("MedicalImageId");

                    b.HasIndex("paitentId");

                    b.ToTable("MedicalImages");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveIngrediantes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsedToCure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.MentalHealthAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncodedAnswers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("patientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("patientId");

                    b.ToTable("MentalHealthAssessments");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.MessageAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttatchmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AttatchmentType")
                        .HasColumnType("integer");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageAttachments");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.PatientHistory", b =>
                {
                    b.Property<long>("History_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("History_Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalIdImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("character(1)");

                    b.Property<string>("Patient_Fhir_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Patient_Id")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneE164")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("History_Id");

                    b.HasIndex("Patient_Fhir_Id", "RecordedAt");

                    b.HasIndex("Patient_Fhir_Id", "RowVersion");

                    b.ToTable("PatientHistory", (string)null);
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.SinaSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("HealthCareProviderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastInteractionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HealthCareProviderId");

                    b.HasIndex("PatientId", "HealthCareProviderId", "Status");

                    b.ToTable("SinaSessions");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.SinaTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrdinalIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("text");

                    b.Property<string>("ToolName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "OrdinalIndex")
                        .IsUnique();

                    b.ToTable("SinaTurns");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.UserDiseaseExperience", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Experince")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApplicationUserId", "DiseaseId");

                    b.HasIndex("DiseaseId")
                        .IsUnique();

                    b.ToTable("UserDiseaseExperiences");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.UserFeedback", b =>
                {
                    b.Property<int>("UserFeedback_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserFeedback_Id"));

                    b.Property<string>("ApplicationUser_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FeedBackCategory")
                        .HasColumnType("integer");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserFeedback_Id");

                    b.HasIndex("ApplicationUser_Id");

                    b.ToTable("UserFeedbacks");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.VerificationCode", b =>
                {
                    b.Property<string>("ApplicationUser_Id")
                        .HasColumnType("text");

                    b.Property<string>("VerificationCodeDigits")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.HasKey("ApplicationUser_Id", "VerificationCodeDigits");

                    b.HasIndex("ApplicationUser_Id")
                        .IsUnique();

                    b.ToTable("VerificationCodes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "static-admin-concurrency-stamp",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "0",
                            ConcurrencyStamp = "static-patient-concurrency-stamp",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        },
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "static-healthcareprovider-concurrency-stamp",
                            Name = "HealthCareProvider",
                            NormalizedName = "HEALTHCAREPROVIDER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Condition.Condition", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.BodySite", null)
                        .WithMany()
                        .HasForeignKey("BodySiteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HealthMate.Infrastructure.Data.Models.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HealthMate.Domain.Aggregates.Encounter.Encounter", null)
                        .WithMany()
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HealthMate.Domain.Aggregates.Patient.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Encounter.Encounter", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.HealthCareProvider", null)
                        .WithMany("Encounters")
                        .HasForeignKey("HealthCareProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HealthMate.Domain.Aggregates.Patient.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Observation.Observation", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.BodySite", null)
                        .WithOne()
                        .HasForeignKey("HealthMate.Domain.Aggregates.Observation.Observation", "BodySiteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HealthMate.Domain.Aggregates.Encounter.Encounter", null)
                        .WithMany()
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HealthMate.Domain.Aggregates.Patient.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Patient.Patient", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("HealthMate.Domain.Aggregates.Patient.Patient", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Patient.PatientAllergy", b =>
                {
                    b.HasOne("HealthMate.Domain.Aggregates.Patient.Patient", "Patient")
                        .WithMany("Allergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Prescription.Prescription", b =>
                {
                    b.HasOne("HealthMate.Domain.Aggregates.Encounter.Encounter", null)
                        .WithMany()
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HealthMate.Domain.Aggregates.Patient.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Prescription.PrescriptionMedicine", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HealthMate.Domain.Aggregates.Patient.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HealthMate.Domain.Aggregates.Prescription.Prescription", null)
                        .WithMany("Medicines")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.Admin", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("HealthMate.Infrastructure.Data.Models.Admin", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.Animal", b =>
                {
                    b.HasOne("HealthMate.Domain.Aggregates.Patient.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("Owner_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.HealthCareProvider", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("HealthMate.Infrastructure.Data.Models.HealthCareProvider", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.LabTest", b =>
                {
                    b.HasOne("HealthMate.Domain.Aggregates.Patient.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("patient");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.LabTestResult", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.LabTestAttribute", "LabTestAttribute")
                        .WithMany("LabTestResults")
                        .HasForeignKey("LabTestAttributeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HealthMate.Infrastructure.Data.Models.LabTest", "LabTest")
                        .WithMany("LabTestResults")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LabTest");

                    b.Navigation("LabTestAttribute");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.MedicalImage", b =>
                {
                    b.HasOne("HealthMate.Domain.Aggregates.Patient.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("paitentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("patient");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.MentalHealthAssessment", b =>
                {
                    b.HasOne("HealthMate.Domain.Aggregates.Patient.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.Message", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthMate.Infrastructure.Data.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.MessageAttachment", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.SinaSession", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.HealthCareProvider", "HealthCareProvider")
                        .WithMany()
                        .HasForeignKey("HealthCareProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HealthMate.Domain.Aggregates.Patient.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HealthCareProvider");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.SinaTurn", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.SinaSession", "Session")
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.UserDiseaseExperience", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("UserDiseaseExperiences")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HealthMate.Infrastructure.Data.Models.Disease", "Disease")
                        .WithOne()
                        .HasForeignKey("HealthMate.Infrastructure.Data.Models.UserDiseaseExperience", "DiseaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Disease");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.UserFeedback", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("UserFeedbacks")
                        .HasForeignKey("ApplicationUser_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.VerificationCode", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("HealthMate.Infrastructure.Data.Models.VerificationCode", "ApplicationUser_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthMate.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HealthMate.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Patient.Patient", b =>
                {
                    b.Navigation("Allergies");
                });

            modelBuilder.Entity("HealthMate.Domain.Aggregates.Prescription.Prescription", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("UserDiseaseExperiences");

                    b.Navigation("UserFeedbacks");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.HealthCareProvider", b =>
                {
                    b.Navigation("Encounters");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.LabTest", b =>
                {
                    b.Navigation("LabTestResults");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.LabTestAttribute", b =>
                {
                    b.Navigation("LabTestResults");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.Message", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("HealthMate.Infrastructure.Data.Models.SinaSession", b =>
                {
                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
